apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: scannable-suse
  name: scannable-suse
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: scannable-suse
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: scannable-suse
    spec:
      containers:
        - image: immauss/scannable:suse
          name: suse
          resources: {}
      restartPolicy: Always
status: {}
